In [1]:
import numpy as np
import pandas as pd
import re
import html
import os.path
from datetime import datetime as dt
import math

from datetime import date, timedelta

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
st_raw = pd.read_excel('C://Users//yan_m//OneDrive//Desktop//Jupyter//IND5003//Project//data//st_raw_10000_01Oct19.xlsx', header=0, encoding = 'unicode_escape')

In [3]:
st_raw.head(2)

,Title,st_3SL2gug,st_28bQfzV,st_3xRimaf,lib_XwnOHoV
0,DestroyTheCoiner,"$AMD Then you remember back a bit, with Obama...","Sep 29th, 4:09 pm",1.0,Bullish
1,GoodNewsBull,"$SPY As you know @Bigmoney1977 is afraid of ""r...","Sep 29th, 3:40 pm",1.0,NaN

In [4]:
st = st_raw.iloc[:,1:4]

In [5]:
st.columns=['message', 'datetime', 'likes']
st.head(1)

                                             message           datetime  likes
0  $AMD  Then you remember back a bit, with Obama...  Sep 29th, 4:09 pm    1.0

In [6]:
st.likes.fillna(0, inplace = True)
st.head(2)

                                             message           datetime  likes
0  $AMD  Then you remember back a bit, with Obama...  Sep 29th, 4:09 pm    1.0
1  $SPY As you know @Bigmoney1977 is afraid of "r...  Sep 29th, 3:40 pm    1.0

Create a time-series

In [7]:
st.datetime = st.datetime.str.replace('th,', '')
st.datetime = st.datetime.str.replace('rd,', '')
st.datetime = st.datetime.str.replace('nd,', '')
st.datetime = st.datetime.str.replace('st,', '')
# can be reduced?

st.datetime = '2019 ' + st.datetime
st.head(2)

,message,datetime,likes
0,"$AMD Then you remember back a bit, with Obama...",2019 Sep 29 4:09 pm,1.0
1,"$SPY As you know @Bigmoney1977 is afraid of ""r...",2019 Sep 29 3:40 pm,1.0

In [8]:
st['datetime'] = st['datetime'].apply(lambda x: dt.strptime(x, "%Y %b %d %I:%M %p"))

In [9]:
st.sort_values(by='datetime', ascending=False)

,message,datetime,likes
0,"$AMD Then you remember back a bit, with Obama...",2019-09-29 16:09:00,1.0
1,"$SPY As you know @Bigmoney1977 is afraid of ""r...",2019-09-29 15:40:00,1.0
2,$UVXY $TVIX $VXX $AAPL $INTC dont miss our lat...,2019-09-29 15:29:00,1.0
3,"$SPY The Bears were hoping for that ""news""to b...",2019-09-29 15:23:00,5.0
4,$AAPL I lived through Watergate and followed i...,2019-09-29 15:17:00,1.0
5,Only a matter of time before Trump is on Twitt...,2019-09-29 15:15:00,3.0
6,$AAPL $QQQ $SPY $ES_F $NQ_F \nIt’s time to dra...,2019-09-29 15:14:00,4.0
7,$FB $AMZN $AAPL $NFLX $GOOG \n\nSunday routine...,2019-09-29 14:43:00,2.0
8,$SPY $AAPL $AMZN $FB $TSLA \nThe Barack Obama ...,2019-09-29 14:05:00,17.0
9,$AAPL \nThis is what you can do on today iPad ...,2019-09-29 13:25:00,3.0
10,"$SPY $AAPL $AMZN Hillary 2020, whose in?...",2019-09-29 12:50:00,2.0
11,$SPY $AAPL $AMZN $QQQ $IWM Socialists Unit...,2019-09-29 10:02:00,2.0
12,$BABA $SPY $AMZN $AAPL - gap up to highs monda...,2019-09-29 09:42:00,2.0
13,$SPY $QQQ $IWM $AAPL,2019-09-29 09:41:00,1.0
14,$AAPL has a Return On Assets of 17.28%. This i...,2019-09-29 09:06:00,0.0
15,$SPY + $AAPL 4H solid rebound off July 30 supp...,2019-09-29 08:53:00,1.0
16,$AAPL waiting for the first battery to explode...,2019-09-29 08:52:00,0.0
17,$AAPL hasn’t fixed their antennas from droppin...,2019-09-29 08:51:00,0.0
18,$AAPL waiting to see how much Apple lovers wil...,2019-09-29 08:45:00,0.0
19,$SPY $QQQ $AAPL $MU $M\nThe Market is fille...,2019-09-29 08:36:00,1.0
20,"Welcome to banana republic $SPY, $AAPL $TQQQ,...",2019-09-29 08:17:00,0.0
21,forbes.com/sites/gordonkell...\n\n$AAPL 👁👁👁👁👁,2019-09-29 07:24:00,1.0
22,$AAPL who remembers trump surprise tweeting an...,2019-09-29 06:41:00,2.0
23,$AAPL trade talks not happening until October ...,2019-09-29 06:40:00,0.0
24,$SPY As long as you didn't short or buy Puts o...,2019-09-29 05:55:00,6.0
25,$AAPL $QQQ $SPYY $ES_F $NQ_F \nIf you have 30...,2019-09-29 05:54:00,0.0
26,Stock Twits is a venue for a lot disingenuous...,2019-09-29 05:42:00,3.0
27,$SPY Bears dont be upset w/ Bulls. Buying Puts...,2019-09-29 05:40:00,6.0
28,$FB Sorry Bears but this was an easy call know...,2019-09-29 05:13:00,10.0
29,$AAPL watch for a move if it breaks $221 to th...,2019-09-29 05:02:00,0.0
...,...,...,...
9373,$AAPL SHORT,2019-09-10 21:11:00,1.0
9378,$AAPL at 699 you probably get the charger only.,2019-09-10 21:10:00,2.0
9380,$AAPL my iPhone 10 just lost 50% of its value!,2019-09-10 21:10:00,4.0
9379,$AAPL iphone pro with ultra ultra wide.,2019-09-10 21:10:00,1.0
9374,$AAPL lower asp’s? Really? That’s not going to...,2019-09-10 21:10:00,1.0
9377,$AAPL raising sell limit to 225✨,2019-09-10 21:10:00,1.0
9376,"Apple event takes bite out of Disney, Roku, Ta...",2019-09-10 21:10:00,1.0
9375,$AAPL Announcing the new IPhone 12 Pro next ye...,2019-09-10 21:10:00,3.0
9386,Great Moments in $AAPL Design History: This ab...,2019-09-10 21:09:00,4.0
9385,$AAPL $699? I can’t wait to see how Wall Stree...,2019-09-10 21:09:00,2.0
9384,$AAPL will this company get some innovation go...,2019-09-10 21:09:00,1.0
9383,Video streaming will soon be free. $AAPL STRE...,2019-09-10 21:09:00,1.0
9381,$AAPL $699 killer price,2019-09-10 21:09:00,2.0
9382,$AAPL $DIS $NFLX These 3 giants are all down t...,2019-09-10 21:09:00,1.0
9387,$AAPL soooo. Now that iPhones are cheaper than...,2019-09-10 21:08:00,1.0
9388,"$AAPL 699 wow, actually competitve",2019-09-10 21:08:00,1.0
9389,$AAPL Pricing products lower than almost all t...,2019-09-10 21:08:00,1.0
9390,$AAPL 699!??? WOAH!!!!,2019-09-10 21:08:00,3.0
9391,$AAPL Yo.. BULLISH on the price,2019-09-10 21:08:00,1.0
9392,$AAPL what $699 why was the last one 1400,2019-09-10 21:08:00,1.0
9398,$AAPL WOW 1 more hour!,2019-09-10 21:07:00,1.0
9401,$AAPL IPHONE 11\n\n•New A13 Bionic -Next Gener...,2019-09-10 21:07:00,1.0
9400,$AAPL is about to explode be ready!!!!🤑🤑,2019-09-10 21:07:00,2.0
9399,$AAPL ding ding,2019-09-10 21:07:00,1.0
9393,$AAPL fuckkk yeah 699? I can afford it hahaha,2019-09-10 21:07:00,2.0
9397,$AAPL $699 I like the price,2019-09-10 21:07:00,3.0
9396,$AAPL $SPY 699 is a steal holy sht,2019-09-10 21:07:00,3.0
9395,$AAPL I'm getting it 699,2019-09-10 21:07:00,1.0
9394,$AAPL,2019-09-10 21:07:00,1.0
9402,$AAPL drops .30 with every video,2019-09-10 21:06:00,1.0

In [10]:
st.set_index('datetime', inplace = True)

In [11]:
st.head(2)

                                                               message  likes
datetime
2019-09-29 16:09:00  $AMD  Then you remember back a bit, with Obama...    1.0
2019-09-29 15:40:00  $SPY As you know @Bigmoney1977 is afraid of "r...    1.0

Cleaning the text message

In [12]:
st['message'] = st['message'].apply(lambda x: html.unescape(x))
st['message'] = st['message'].apply(lambda x: re.sub(r'(www\.|https?://).*?(\s|$)|@.*?(\s|$)|\$.*?(\s|$)|\d|\%|\\|/|-|_', ' ', x))
st['message'] = st['message'].apply(lambda x: re.sub(r'\s+', ' ', x))

Initialize Sentiment Analyzer

In [13]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

import csv

In [14]:
nltk.download('vader_lexicon')
sia = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\yan_m\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [15]:
# stock market lexicon
stock_lex = pd.read_csv('C://Users//yan_m//OneDrive//Desktop//Jupyter//IND5003//Project//data//stock_lex.csv')

In [16]:
stock_lex['sentiment'] = (stock_lex['Aff_Score'] + stock_lex['Neg_Score'])/2
stock_lex = dict(zip(stock_lex.Item, stock_lex.sentiment))
stock_lex = {k:v for k,v in stock_lex.items() if len(k.split(' '))==1}
stock_lex_scaled = {}
for k, v in stock_lex.items():
    if v > 0:
        stock_lex_scaled[k] = v / max(stock_lex.values()) * 4
    else:
        stock_lex_scaled[k] = v / min(stock_lex.values()) * -4

In [17]:
# Loughran and McDonald
positive = []
with open('C://Users//yan_m//OneDrive//Desktop//Jupyter//IND5003//Project//data//lm_positive.csv', 'r') as f:
    reader = csv.reader(f)
    for row in reader:
        positive.append(row[0].strip())
    
negative = []
with open('C://Users//yan_m//OneDrive//Desktop//Jupyter//IND5003//Project//data//lm_negative.csv', 'r') as f:
    reader = csv.reader(f)
    for row in reader:
        entry = row[0].strip().split(" ")
        if len(entry) > 1:
            negative.extend(entry)
        else:
            negative.append(entry[0])

In [18]:
final_lex = {}
# final_lex.update({word:2.0 for word in positive})
# final_lex.update({word:-2.0 for word in negative})
final_lex.update(stock_lex_scaled)
final_lex.update(sia.lexicon)
sia.lexicon = final_lex

Conducting the SA

In [19]:
# demonstrating how its used
text = st.message[4]
score = sia.polarity_scores(text)['compound']

print('The text:\"{0}\" has a score of {1}.'.format(text, score))

The text:" I lived through Watergate and followed it closely. Apparently the Trumps are ignorant of history. When you are ignorant of history, knocking down your claims is like shooting fish in a barrel." has a score of -0.4649.

In [20]:
# demonstrating how sia.polarity_score is used
score = sia.polarity_scores(text)
score

{'neg': 0.474, 'neu': 0.269, 'pos': 0.257, 'compound': -0.4649}

In [21]:
st['polarity_score'] = st['message'].apply(lambda x: sia.polarity_scores(x)['compound'])

In [22]:
st.polarity_score = pd.to_numeric(st.polarity_score)

In [23]:
st[st.polarity_score == 0].sample(3)
# notice that all the text with 0 score are gibberish, emoticons or blanks after cleaning

                       message  likes  polarity_score
datetime
2019-09-12 04:02:00               2.0             0.0
2019-09-18 08:39:00   Powell =    2.0             0.0
2019-09-13 01:17:00               9.0             0.0

In [24]:
st.drop(st[st.polarity_score == 0].index, inplace = True)
st[st.polarity_score == 0]

Empty DataFrame
Columns: [message, likes, polarity_score]
Index: []

In [25]:
st.polarity_score.describe()

count    8381.000000
mean        0.275738
std         0.435324
min        -0.973200
25%        -0.001600
50%         0.302200
75%         0.633700
max         0.995000
Name: polarity_score, dtype: float64

In [26]:
print('{0} number of comments in Stocktwits collected from ({1}) to ({2}) will be processed.'.format(len(st), st.index[0], st.index[-1]))

8381 number of comments in Stocktwits collected from (2019-09-29 16:09:00) to (2019-09-10 21:06:00) will be processed.

Aggregate them into daily

Just average of them all

In [27]:
sa_daily = st.groupby(st.index.date).polarity_score.mean()
sa_daily = pd.DataFrame(sa_daily)
sa_daily.head()

            polarity_score
2019-09-10        0.311241
2019-09-11        0.347112
2019-09-12        0.283504
2019-09-13        0.240032
2019-09-14        0.311894

In [28]:
sa = st.groupby([st.index.date, st.index.hour]).polarity_score.mean()

In [29]:
sa = pd.DataFrame(sa)
sa_hrly = sa.unstack()
sa_hrly.head(2)

           polarity_score                                                  \
datetime               0         1         2       3         4         5
2019-09-10            NaN       NaN       NaN     NaN       NaN       NaN
2019-09-11       0.412477  0.399679  0.357439  0.2205  0.430382  0.398306

                                                  ...                      \
datetime          6         7         8       9   ...        14        15
2019-09-10       NaN       NaN       NaN     NaN  ...       NaN       NaN
2019-09-11  0.487494  0.486581  0.533808  0.2769  ...  0.293682  0.370549

                                                                       \
datetime          16       17        18        19        20        21
2019-09-10       NaN      NaN       NaN       NaN       NaN  0.282418
2019-09-11  0.177584  0.43338  0.271156  0.353637  0.344581  0.328075


datetime          22        23
2019-09-10  0.322983  0.376174
2019-09-11  0.334656  0.349438

[2 rows x 24 columns]

In [30]:
SA = pd.concat([sa_daily, sa_hrly], axis=1, sort=False)
SA

,polarity_score,"(polarity_score, 0)","(polarity_score, 1)","(polarity_score, 2)","(polarity_score, 3)","(polarity_score, 4)","(polarity_score, 5)","(polarity_score, 6)","(polarity_score, 7)","(polarity_score, 8)",...,"(polarity_score, 14)","(polarity_score, 15)","(polarity_score, 16)","(polarity_score, 17)","(polarity_score, 18)","(polarity_score, 19)","(polarity_score, 20)","(polarity_score, 21)","(polarity_score, 22)","(polarity_score, 23)"
2019-09-10,0.311241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.282418,0.322983,0.376174
2019-09-11,0.347112,0.412477,0.399679,0.357439,0.220500,0.430382,0.398306,0.487494,0.486581,0.533808,...,0.293682,0.370549,0.177584,0.433380,0.271156,0.353637,0.344581,0.328075,0.334656,0.349438
2019-09-12,0.283504,0.459084,0.291404,0.356428,0.357334,0.410096,0.353194,0.217150,0.378222,0.233700,...,0.363990,0.401854,0.276955,0.302141,0.325183,0.247032,0.187107,0.437714,0.180030,0.188412
2019-09-13,0.240032,0.217770,0.239337,0.281594,0.375841,0.157436,0.445511,0.014057,0.103957,0.445200,...,0.292054,0.238780,0.206943,0.255236,0.265227,0.249534,0.291060,0.243035,0.231625,0.131231
2019-09-14,0.311894,0.124377,0.280317,0.368900,0.292271,0.471714,0.112600,0.306025,0.167520,0.483650,...,0.242708,0.356588,0.363860,0.558625,0.264960,0.508322,0.424486,0.486133,0.236517,0.266050
2019-09-15,0.260324,0.303833,0.210056,0.803067,0.139686,0.149686,0.243000,0.089933,-0.165450,0.290200,...,0.489000,0.342771,0.100580,0.846100,0.244630,0.223243,0.516962,-0.001833,0.286910,0.282900
2019-09-16,0.285930,0.360064,0.339709,0.386848,0.112948,0.226200,0.318308,0.095717,0.522283,0.065886,...,0.229394,0.525329,0.275611,0.260675,0.306958,0.240350,0.358137,0.314685,0.157457,0.328112
2019-09-17,0.229130,0.426310,0.347212,0.099920,0.209821,0.455117,0.366717,0.089650,-0.126033,0.364960,...,0.385921,0.243838,0.170219,0.094523,0.330011,0.158524,0.158087,0.250400,0.142928,0.195256
2019-09-18,0.264486,0.449453,0.384606,0.330362,0.381645,-0.054825,0.142500,0.513750,0.663850,0.196800,...,0.399535,0.278519,0.166989,0.204659,0.329721,0.280339,0.265722,0.170138,0.254134,0.281231
2019-09-19,0.253015,0.209914,0.446617,0.012890,0.443611,0.292806,0.379112,0.290477,-0.157640,0.307833,...,0.282909,0.370693,0.294958,0.317269,0.195604,0.211800,0.084688,0.281148,0.201203,0.344539
2019-09-20,0.237334,0.151892,0.421483,0.429427,0.380720,0.293643,0.463143,0.165567,0.385457,NaN,...,0.192556,0.351121,0.306533,0.284845,0.104673,0.079843,0.193103,0.256097,0.147450,0.287305
2019-09-21,0.314499,0.085025,0.427800,0.192123,0.181282,0.524820,0.014983,0.577333,0.384320,0.442100,...,0.325440,0.580033,0.384875,0.571650,0.449640,0.466483,0.285775,0.372313,0.540600,0.269800
2019-09-22,0.305714,0.443367,0.365328,0.034817,0.043243,0.177814,0.210467,0.247600,0.583733,0.213240,...,0.449175,0.548300,0.464237,0.341300,-0.057933,0.738850,0.187280,0.392086,0.202064,0.393960
2019-09-23,0.258283,0.353514,0.398669,0.176792,0.228546,0.506786,0.435750,-0.169633,0.206167,0.836600,...,0.351195,0.337105,0.214616,0.226370,0.293076,0.357563,0.322032,0.272836,0.202910,0.096696
2019-09-24,0.266352,0.161367,0.432250,0.192409,0.308978,0.215857,0.505980,0.549425,0.391920,0.384250,...,0.273755,0.449829,0.291030,0.254559,0.252382,0.177181,0.164777,0.315457,0.160411,0.185967
2019-09-25,0.278631,0.068990,0.275836,0.539978,0.361792,0.141408,0.148440,0.500360,0.336133,0.745150,...,0.340319,0.299889,0.336200,0.283616,0.249202,0.260543,0.279392,0.289029,0.348421,0.141858
2019-09-26,0.277233,0.302894,0.480654,0.295829,0.528112,-0.139140,0.249918,0.307150,0.367160,0.755500,...,0.186827,0.291226,0.332786,0.204733,0.305820,0.273528,0.170288,0.306517,0.187346,0.210426
2019-09-27,0.289458,0.300173,0.192300,0.423308,0.402014,0.414280,0.257600,0.237375,0.875600,0.210050,...,0.407280,0.418156,0.398905,0.261650,0.099972,0.194998,0.309993,0.261802,0.450424,0.248331
2019-09-28,0.306783,0.317425,-0.057300,0.564525,0.078050,0.449282,0.283400,0.683400,0.311117,0.330967,...,0.015850,0.376143,0.008137,0.031525,0.407113,0.404260,0.680800,0.232580,0.531500,-0.086800
2019-09-29,0.343161,-0.026400,0.348833,0.709700,NaN,NaN,0.657350,0.602350,NaN,0.142083,...,0.876050,-0.233133,0.869700,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
SA.to_csv('C://Users//yan_m//OneDrive//Desktop//Jupyter//IND5003//Project//data//Sentiment_Scores_01Oct19.csv', index=True)